# 실기 대비
# 실전 문제풀이
# set 4

## 1) 데이터 및 시나리오

### 디지털프라자 매출 데이터

> 디지털프라자 A지점에서 최근 연휴 직전에 재고 처리와 매출 신장을 위해 대대적인 할인 행사를 하였다.  
> 하루만 반짝 진행한 행사에서 예상보다 많은 손님이 방문했고 이번에 발생한 매출데이터를 취합하여 향후 발송할 판촉물에 들어갈 컨텐츠를 기획하고자 한다.  
> 취합한 데이터는 다음과 같고 한 개의 행이 물품 1개 구매 내역이다.

### 데이터 개요

| 파일명 | 행 | 열 | 인코딩 |
|---|---:|---:|---|
| `sales_pos.csv` | 550068 | 11 | UTF-8 |

## 1) 데이터 및 시나리오

### 변수 상세

| 변수명 | 유형 | 설명 |
|---|---|---|
| `user` | int | 고객 식별자 |
| `prod` | string | 상품 식별자 |
| `gender` | string | 성별 |
| `age_group` | string | 연령대 |
| `job` | int | 직업 구분 |
| `city` | string | 도시 유형 구분 |
| `marital` | int | 결혼 여부 `(1: 결혼)` |
| `prod_cat1` | int | 상품 카테고리 `(1차)` |
| `prod_cat2` | int | 상품 카테고리 `(2차)` |
| `prod_cat3` | int | 상품 카테고리 `(3차)` |
| `purchase` | int | 결제 금액 |

## 2) 문제

### 필요 라이브러리 함수 및 클래스 목록

| 목록 |
|---|
| `from sklearn.preprocessing import MinMaxScaler` |
| `from sklearn.cluster import KMeans` |
| `from sklearn.metrics import silhouette_score` 

In [1]:
import numpy as np
import pandas as pd

from sklearn.preprocessing import MinMaxScaler
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

In [3]:
df = pd.read_csv('../../dataset/sales_pos.csv')

#SCDI
display(df.shape)
display(df.columns)
display(df.dtypes)
display(df.isna().sum())

(550068, 11)

Index(['user', 'prod', 'gender', 'age_group', 'job', 'city', 'marital',
       'prod_cat1', 'prod_cat2', 'prod_cat3', 'purchase'],
      dtype='object')

user           int64
prod          object
gender        object
age_group     object
job            int64
city          object
marital        int64
prod_cat1      int64
prod_cat2    float64
prod_cat3    float64
purchase       int64
dtype: object

user              0
prod              0
gender            0
age_group         0
job               0
city              0
marital           0
prod_cat1         0
prod_cat2    173638
prod_cat3    383247
purchase          0
dtype: int64

### Q01.

상품별 매출액(`purchase`)을 합산하여 그 매출액이 가장 큰 상품을 확인하고 해당 상품을 가장 많이 구매하는 직업(`job`)을 확인하시오.

※ 분석 결과를 기반으로 `job` 변수의 번호를 최종 출력하시오.  
※ 직업 확인시 상품 구매 개수를 기준으로 확인하시오. `(정답 예시: 1)`

In [18]:
df_q1 = df.copy()
cols_q1 = ['prod', 'purchase' ,'job']
df_q1_1 = df_q1[cols_q1]
display(df_q1_1)
ser_sum = df_q1_1.groupby(['prod'])['purchase'].sum()
display(ser_sum.sort_values(ascending = False))
display(ser_sum.max(), ser_sum.idxmax())

df_q1_2 = df_q1_1.loc[df_q1_1['prod'] == ser_sum.idxmax(), :]
display(df_q1_2['job'].value_counts().idxmax())


,prod,purchase,job
0,P00069042,8370,10
1,P00248942,15200,10
2,P00087842,1422,10
3,P00085442,1057,10
4,P00285442,7969,16
...,...,...,...
550063,P00372445,368,13
550064,P00375436,371,1
550065,P00375436,137,15
550066,P00375436,365,1


prod
P00025442    27995166
P00110742    26722309
P00255842    25168963
P00059442    24338343
P00184942    24334887
               ...   
P00012942        1717
P00325342        1656
P00353042        1545
P00309042         726
P00091742         405
Name: purchase, Length: 3631, dtype: int64

27995166

'P00025442'

4

### Q02.

결혼 여부(`marital`)에 따라 구매하는 물품의 종류가 많이 차이 나는지 확인하고자 한다.  
비교적 신혼부부가 많은 26-35세 그룹을 대상으로 각 고객의 구매물품 카테고리 개수를 산출하고 결혼여부별 그 평균값의 차이를 산출하시오.

※ 구매 물품의 카테고리 개수 산출에는 `prod_cat1`, `prod_cat2`, `prod_cat3` 변수를 사용한다.  
※ 카테고리 관련 변수의 결측치는 0으로 대체한다.  
※ 결측치를 대체한 데이터까지 포함하여 문제를 풀이하시오.  
※ 카테고리 관련 변수의 처리 예시는 다음과 같다.

| `prod_cat1` | `prod_cat2` | `prod_cat3` | `prod_cat` |
|---:|---:|---:|---|
| 1 | 2 | 0 | `1-2-0` |
| 8 | 0 | 0 | `8-0-0` |

※ 고객 식별자가 1인 고객은 총 21개 카테고리의 물품을 구매하였다.  
※ 정답은 절대값을 반올림하여 소수점 둘째 자리까지 출력하시오. `(정답 예시: 0.12)`

In [ ]:
df_q2 = df.copy()
display(df_q2['prod_cat1'].unique(), df_q2['prod_cat2'].unique(), df_q2['prod_cat3'].unique())
display(df_q2['age_group'].unique())

cols_q2 = ['user', 'marital','prod_cat1','prod_cat2','prod_cat3','age_group']
df_q2_1 = df_q2[cols_q2].copy()
df_q2_1 = df_q2_1.fillna(0)
df_q2_1[['prod_cat1','prod_cat2','prod_cat3']] = df_q2_1[['prod_cat1','prod_cat2','prod_cat3']].astype(int).astype(str)
display(df_q2_1['prod_cat1'].unique(), df_q2_1['prod_cat2'].unique(), df_q2_1['prod_cat3'].unique())

df_q2_1['prod_cat'] = df_q2_1['prod_cat1'] + '-' + df_q2_1['prod_cat2'] + '-' + df_q2_1['prod_cat3']
display(df_q2_1.shape)

df_q2_2635 = df_q2_1.loc[df_q2_1['age_group'] == '26-35', :].copy()
display(df_q2_2635.shape)
display(df_q2_2635)

 #고객별 구매물품 카테고리 개수 산출
df_q2_gb = df_q2_2635.groupby(['user','marital'])['prod_cat'].nunique() #user-marital은 1:1임 결혼하면서 안한 사람이 없지
display(df_q2_gb)

#결혼여부 별 평균값
df_q2_gb = df_q2_gb.reset_index(name='count') #reset_index() 하니 바로 prod_cat이 만들어진 이유?
display(df_q2_gb)
df_q2_gb2 = df_q2_gb.groupby('marital')['count'].mean()
marital_false = df_q2_gb2[0]
marital_true = df_q2_gb2[1]
display(round(abs(marital_false-marital_true), 2))

array([ 3,  1, 12,  8,  5,  4,  2,  6, 14, 11, 13, 15,  7, 16, 18, 10, 17,
        9, 20, 19], dtype=int64)

array([nan,  6., 14.,  2.,  8., 15., 16., 11.,  5.,  3.,  4., 12.,  9.,
       10., 17., 13.,  7., 18.])

array([nan, 14., 17.,  5.,  4., 16., 15.,  8.,  9., 13.,  6., 12.,  3.,
       18., 11., 10.])

array(['0-17', '55+', '26-35', '46-50', '51-55', '36-45', '18-25'],
      dtype=object)

array(['3', '1', '12', '8', '5', '4', '2', '6', '14', '11', '13', '15',
       '7', '16', '18', '10', '17', '9', '20', '19'], dtype=object)

array(['0', '6', '14', '2', '8', '15', '16', '11', '5', '3', '4', '12',
       '9', '10', '17', '13', '7', '18'], dtype=object)

array(['0', '14', '17', '5', '4', '16', '15', '8', '9', '13', '6', '12',
       '3', '18', '11', '10'], dtype=object)

(550068, 7)

(219587, 7)

,user,marital,prod_cat1,prod_cat2,prod_cat3,age_group,prod_cat
5,3,0,1,2,0,26-35,1-2-0
9,5,1,8,0,0,26-35,8-0-0
10,5,1,5,11,0,26-35,5-11-0
11,5,1,8,0,0,26-35,8-0-0
12,5,1,8,0,0,26-35,8-0-0
...,...,...,...,...,...,...,...
550058,6024,1,20,0,0,26-35,20-0-0
550059,6025,0,19,0,0,26-35,19-0-0
550061,6029,1,20,0,0,26-35,20-0-0
550064,6035,0,20,0,0,26-35,20-0-0


user  marital
3     0           18
5     1           43
8     1           32
9     0           31
11    0           34
                ... 
6030  1           33
6034  0            8
6035  0           61
6036  1          123
6040  0           60
Name: prod_cat, Length: 2053, dtype: int64

,user,marital,count
0,3,0,18
1,5,1,43
2,8,1,32
3,9,0,31
4,11,0,34
...,...,...,...
2048,6030,1,33
2049,6034,0,8
2050,6035,0,61
2051,6036,1,123


0.13

### Q03.

고객 5891명을 군집화 하여 각 군집별로 마케팅 전략을 수립하고자 한다.  
다음에 제시된 변수를 대상으로 k-means 군집분석을 실시하고 7개 군집으로 분석했을 때 Silhouette score를 산출하시오.

#### 독립변수

| 독립변수 |
|---|
| 성별 |
| 나이 |
| 직업 |
| 도시 |
| 결혼 여부 |
| 구매 상품 종류수 |
| 총 구매금액 |

※ 구매 상품 종류수 변수는 `prod` 변수를 참고하여 생성하시오.  
※ 성별 변수는 `gender` 변수에서 `M`을 1, `F`를 0으로 변환하여 사용하시오.  
※ 나이는 `age_group` 변수에서 나이가 가장 적은 그룹을 0으로 지정하고 가장 나이가 많은 그룹은 6으로 지정하는 방식으로 순서형 변수로 변환하시오.  
※ 직업과 도시 변수는 One Hot Encoding 변환하여 사용하시오.  
※ 군집 분석에 사용되는 변수는 총 29개이며 MinMax 정규화 후 분석하시오.  
※ seed는 `123`으로 지정하시오.  
※ 결과는 반올림하여 소수점 둘째 자리까지 출력하시오. `(정답 예시: 0.12)`

In [ ]:
df_q3 = df.copy()
display(df_q3.columns)
cols_X = ['gender', 'age_group', 'job', 'city', 'marital', 'kind', 'purchase']


df_q3_agg = df_q3.groupby('user').agg(
    gender=('gender', 'first'),
    age_group = ('age_group','first'),
    job = ('job', 'first'),
    city = ('city', 'first'),
    marital = ('marital', 'first'),
    kind = ('prod', 'nunique'),
    purchase = ('purchase', 'sum')
) 
display(df_q3_agg) #user 가 index가 되므로 이 df 자체가 X가 가능하다. reset_index를 하지말기

#gender
df_q3_agg['gender'] = df_q3_agg['gender'].replace({
    "M" : 1,
    "F" : 0
}).astype(int).copy() #replace().astype() 은 셋트!
display(df_q3_agg)

#age_group
display(df_q3_agg['age_group'].value_counts())
arr = df_q3_agg['age_group'].unique()
arr = np.sort(arr) #array는 numpy의 sort를 이용하기! 오름차순 내림차순은, series, df 은 sort_values()
display(arr)
ser = pd.Series(arr)
display(ser)
dict_age_group = dict(zip(ser, ser.index))
display(dict_age_group)
df_q3_agg['age_group'] = df_q3_agg['age_group'].replace(dict_age_group).astype(int).copy()
display(df_q3_agg['age_group'].value_counts())

#job,city
df_q3_ohe = pd.get_dummies(df_q3_agg, columns=['job','city']).copy()
display(df_q3_ohe.shape, df_q3_ohe.columns)

#DNME

#D
X = df_q3_ohe.copy()

#N
scaler = MinMaxScaler()
X_n = scaler.fit_transform(X) #fit-최대최소,transform-fit에 맞게 정규화

#M
model = KMeans(n_clusters = 7, random_state = 123)
model.fit(X_n)
pred_y = model.predict(X_n)
display(pred_y)
#E
sil = silhouette_score(X_n, pred_y) #이 파라미터들을 왜 넣는가
display(round(sil, 2))

Index(['user', 'prod', 'gender', 'age_group', 'job', 'city', 'marital',
       'prod_cat1', 'prod_cat2', 'prod_cat3', 'purchase'],
      dtype='object')

,gender,age_group,job,city,marital,kind,purchase
user,,,,,,,
1,F,0-17,10,A,0,35,334093
2,M,55+,16,C,0,77,810472
3,M,26-35,15,A,0,29,341635
4,M,46-50,7,B,1,14,206468
5,M,26-35,20,A,1,106,821001
...,...,...,...,...,...,...,...
6036,F,26-35,15,B,1,514,4116058
6037,F,46-50,1,C,0,122,1119538
6038,F,55+,1,C,0,12,90034


,gender,age_group,job,city,marital,kind,purchase
user,,,,,,,
1,0,0-17,10,A,0,35,334093
2,1,55+,16,C,0,77,810472
3,1,26-35,15,A,0,29,341635
4,1,46-50,7,B,1,14,206468
5,1,26-35,20,A,1,106,821001
...,...,...,...,...,...,...,...
6036,0,26-35,15,B,1,514,4116058
6037,0,46-50,1,C,0,122,1119538
6038,0,55+,1,C,0,12,90034


26-35    2053
36-45    1167
18-25    1069
46-50     531
51-55     481
55+       372
0-17      218
Name: age_group, dtype: int64

array(['0-17', '18-25', '26-35', '36-45', '46-50', '51-55', '55+'],
      dtype=object)

0     0-17
1    18-25
2    26-35
3    36-45
4    46-50
5    51-55
6      55+
dtype: object

{'0-17': 0,
 '18-25': 1,
 '26-35': 2,
 '36-45': 3,
 '46-50': 4,
 '51-55': 5,
 '55+': 6}

2    2053
3    1167
1    1069
4     531
5     481
6     372
0     218
Name: age_group, dtype: int64

(5891, 29)

Index(['gender', 'age_group', 'marital', 'kind', 'purchase', 'job_0', 'job_1',
       'job_2', 'job_3', 'job_4', 'job_5', 'job_6', 'job_7', 'job_8', 'job_9',
       'job_10', 'job_11', 'job_12', 'job_13', 'job_14', 'job_15', 'job_16',
       'job_17', 'job_18', 'job_19', 'job_20', 'city_A', 'city_B', 'city_C'],
      dtype='object')

array([4, 5, 4, ..., 2, 1, 6])

0.18